-- ============================================================================
-- Importação do comparativo técnico Mahindra (especificacoes_detalhadas) — 2026-06-24
--
-- Pré-requisito: rodar antes o supabase-especificacoes-detalhadas.sql (cria a coluna).
-- Rodar em: https://supabase.com/dashboard/project/citrhumdkfivdzbmayde/sql/new
--
-- PASSO 1: confira o mapeamento modelo->ficha (slug) antes dos UPDATEs.
-- ============================================================================

select id, slug, titulo from catalogo_produtos
where slug ilike 'mahindra-%' order by slug;

-- PASSO 2: aplica as specs por modelo.

-- 2025 -> mahindra-2025 (10 grupos)
update catalogo_produtos set especificacoes_detalhadas = '[{"grupo":"Motor","itens":[{"label":"Motor","valor":"MAHINDRA MDI 1365"},{"label":"Tipo","valor":"Diesel, refrigerado a água, injeção direta, aspirado"},{"label":"Potencia Maxima","valor":"25 @ 2300 RPM"},{"label":"Torque Máximo","valor":"86,3 Nm @ 1400 rpm"},{"label":"Cilindros/Cilindradas","valor":"2/1366 cm³"},{"label":"Aceleração","valor":"Mecânica por alavanca manual ou pedal"},{"label":"Filtro de ar","valor":"A seco, com filtro de segurança"}]},{"grupo":"Embreagem","itens":[{"label":"Tipo","valor":"Disco simples"},{"label":"Acionamento","valor":"Mecânico por pedal"}]},{"grupo":"Tomada de potência (TDP)","itens":[{"label":"Tipo","valor":"Dependente"},{"label":"Velocidade","valor":"540 @ 2046 RPM & 540E @ 1654 RPM"},{"label":"Acoplamento","valor":"Mecânico"},{"label":"Potencia TDP","valor":"22 cv"}]},{"grupo":"Transmissão","itens":[{"label":"Tipo","valor":"Mecânica com reversor(cambio seco)"},{"label":"Posição das alavancas","valor":"Lateral"},{"label":"Marchas","valor":"8 marchas à frente e 4 marchas à ré"},{"label":"Reversor","valor":"Acionamento mecânico"},{"label":"Tração dianteira","valor":"Mecânico por pedal"}]},{"grupo":"Sistema hidráulico","itens":[{"label":"Tipo","valor":"Centro aberto, mecânico com controle de posição e de profundidade"},{"label":"Pressão máxima (kgf/cm²)","valor":"190"},{"label":"Vazão da bomba (L/min)","valor":"Vazão de 16 litros/minuto"},{"label":"Capacidade de levante no olhal (kg)","valor":"750 Kg"},{"label":"Válvulas de controle remoto","valor":"N.D."}]},{"grupo":"Freios","itens":[{"label":"Tipo","valor":"Disco simples seco"},{"label":"Acionamento","valor":"Mecânico"},{"label":"Freio de estacionamento","valor":"Trava pedais/freios sobre as rodas traseiras"}]},{"grupo":"Direção","itens":[{"label":"Tipo","valor":"Manual"}]},{"grupo":"Capacidades","itens":[{"label":"Tanque de combustível","valor":"22 Litros"},{"label":"Tensão sist. elétrico","valor":"12 V"},{"label":"Alternador","valor":"12 V/36 Ah"},{"label":"Motor de partida","valor":"12 V/2 kW"},{"label":"Bateria","valor":"12 V/65 Ah"}]},{"grupo":"Dimensões","itens":[{"label":"Pneus dianteiros","valor":"6.0x14 R1"},{"label":"Pneus traseiros","valor":"8.3x24 R1"},{"label":"Raio de giro c/ uso freio","valor":"2300 mm"},{"label":"Raio de giro s/ uso freio","valor":"2600 mm"},{"label":"Contrapesos dianteiros","valor":"2 X 45 kg"},{"label":"Contrapesos traseiros","valor":"2 X 50 kg"},{"label":"Comprimento máximo","valor":"2746 mm"},{"label":"Distância entre eixos","valor":"1570 mm"},{"label":"Altura mínima do solo","valor":"285 mm"},{"label":"Altura máxima (até o volante)","valor":"1373 mm"},{"label":"Peso em ordem de marcha (embarque)","valor":"1020 kg"},{"label":"Peso em ordem de marcha (lastrado)","valor":"1425 kg"}]},{"grupo":"Posto de operação","itens":[{"label":"Tipo","valor":"Semi-plataforma com ROPS"}]}]'::jsonb where slug = 'mahindra-2025';

-- 5050 -> mahindra-5050 (11 grupos)
update catalogo_produtos set especificacoes_detalhadas = '[{"grupo":"Motor","itens":[{"label":"Motor","valor":"MAHINDRA MTDHI30"},{"label":"Potencia Maxima","valor":"49,3@2100RPM"},{"label":"Torque Máximo","valor":"198@1260"},{"label":"Cilindros/Cilindradas","valor":"4 / 2980 cm³"}]},{"grupo":"Embreagem","itens":[{"label":"Tipo","valor":"Dupla"},{"label":"Diâmetro do disco (mm)","valor":"280"}]},{"grupo":"Tomada de potência (TDP)","itens":[{"label":"Tipo","valor":"Independente"},{"label":"Velocidade","valor":"540 @ 1810 RPM / 540E @ 1520 RPM"},{"label":"Potencia TDP","valor":"45cv"}]},{"grupo":"Transmissão","itens":[{"label":"Marchas","valor":"12F + 12R"},{"label":"Reversor","valor":"Mecânico sincronizado"},{"label":"Tração dianteira","valor":"Comando Mecanico Manual"},{"label":"Bloqueio do diferencial","valor":"Comando Mecanico Manual por pedal"}]},{"grupo":"Sistema hidráulico","itens":[{"label":"Pressão máxima (kgf/cm²)","valor":"200"},{"label":"Vazão da bomba (L/min)","valor":"27,3l/min"},{"label":"Capacidade de levante no olhal (kg)","valor":"1700kg"},{"label":"Válvulas de controle remoto","valor":"2"}]},{"grupo":"Freios","itens":[{"label":"Tipo","valor":"Discos imersos e resfriados em banho de oleo"}]},{"grupo":"Direção","itens":[{"label":"Tipo","valor":"Hidrostatica com circuito hidraulico independente"},{"label":"Bomba direção","valor":"Engrenagens, vazão de 17litros/minuto"}]},{"grupo":"Capacidades","itens":[{"label":"Tanque de combustível","valor":"60l"},{"label":"Alternador","valor":"12 V/45 Ah"},{"label":"Motor de partida","valor":"12 V/2 kW"},{"label":"Bateria","valor":"12 V/80 Ah"}]},{"grupo":"Dimensões","itens":[{"label":"Pneus dianteiros","valor":"9.5 X 20R1"},{"label":"Pneus traseiros","valor":"14.9 X 28R1"},{"label":"Raio de giro c/ uso freio","valor":"3500mm"},{"label":"Raio de giro s/ uso freio","valor":"3900mm"},{"label":"Contrapesos dianteiros","valor":"6x27 kg"},{"label":"Contrapesos traseiros","valor":"2x50 kg"},{"label":"Comprimento máximo","valor":"3445"},{"label":"Distância entre eixos","valor":"1980"},{"label":"Altura mínima do solo","valor":"351"},{"label":"Altura máxima (até o volante)","valor":"2240"},{"label":"Peso em ordem de marcha (embarque)","valor":"2402"},{"label":"Peso em ordem de marcha (lastrado)","valor":"2710kg"}]},{"grupo":"Posto de operação","itens":[{"label":"Tipo","valor":"Plataforma com teto e ROPS"}]},{"grupo":"Itens de série","itens":[{"label":"Retrovisor direito","valor":"X"},{"label":"Farol de Trabalho Traseiro","valor":"X"}]}]'::jsonb where slug = 'mahindra-5050';

-- 6060 -> mahindra-6060 (9 grupos)
update catalogo_produtos set especificacoes_detalhadas = '[{"grupo":"Motor","itens":[{"label":"Motor","valor":"MAHINDRA MSI 457"},{"label":"Potencia Maxima","valor":"57cv@2100RPM"},{"label":"Torque Máximo","valor":"232@1260"},{"label":"Cilindros/Cilindradas","valor":"4/3533 cm³"}]},{"grupo":"Embreagem","itens":[{"label":"Tipo","valor":"Cerametalica Dupla"},{"label":"Diâmetro do disco (mm)","valor":"304,8"}]},{"grupo":"Tomada de potência (TDP)","itens":[{"label":"Velocidade","valor":"540 @1993 RPM/540E @ 1459 RPM"},{"label":"Potencia TDP","valor":"49cv"}]},{"grupo":"Transmissão","itens":[{"label":"Tipo","valor":"Mecanica sincronizada com reversor"},{"label":"Marchas","valor":"20F+20(5 velocidades  sincronizadas com 4 grupos (Redutor = C, L-M-H)"}]},{"grupo":"Sistema hidráulico","itens":[{"label":"Pressão máxima (kgf/cm²)","valor":"190"},{"label":"Vazão da bomba (L/min)","valor":"42l/min"},{"label":"Capacidade de levante no olhal (kg)","valor":"2200kg"},{"label":"Válvulas de controle remoto","valor":"2 válvulas de dupla ação (standard)"}]},{"grupo":"Capacidades","itens":[{"label":"Tanque de combustível","valor":"60l"},{"label":"Lubrificação","valor":"Por bomba independente, com vazão de 15 litros/minuto"},{"label":"Motor de partida","valor":"12 V/2.2 kW"},{"label":"Bateria","valor":"12 V/88 Ah"}]},{"grupo":"Dimensões","itens":[{"label":"Comprimento máximo","valor":"3850mm"},{"label":"Distância entre eixos","valor":"2220mm"},{"label":"Peso em ordem de marcha (embarque)","valor":"2970"}]},{"grupo":"Posto de operação","itens":[{"label":"Tipo","valor":"Plataforma com teto e ROPS"}]},{"grupo":"Itens de série","itens":[{"label":"Retrovisor direito","valor":"X"},{"label":"Painel de instrumentos digitais","valor":"X"},{"label":"Farol de Trabalho Traseiro","valor":"X"}]}]'::jsonb where slug = 'mahindra-6060';

-- 6065 -> mahindra-6065 (8 grupos)
update catalogo_produtos set especificacoes_detalhadas = '[{"grupo":"Motor","itens":[{"label":"Motor","valor":"MAHINDRA MSI 465"},{"label":"Potencia Maxima","valor":"65cv@2100RPM"},{"label":"Torque Máximo","valor":"250@1260rpm"},{"label":"Cilindros/Cilindradas","valor":"4/3822 cm³"}]},{"grupo":"Embreagem","itens":[{"label":"Diâmetro do disco (mm)","valor":"304,8"}]},{"grupo":"Tomada de potência (TDP)","itens":[{"label":"Velocidade","valor":"540 @1993 RPM/540E @ 1459 RPM"},{"label":"Potencia TDP","valor":"57cv"}]},{"grupo":"Sistema hidráulico","itens":[{"label":"Pressão máxima (kgf/cm²)","valor":"190"},{"label":"Vazão da bomba (L/min)","valor":"58l/min"},{"label":"Capacidade de levante no olhal (kg)","valor":"2600 kg (standard)"}]},{"grupo":"Capacidades","itens":[{"label":"Tanque de combustível","valor":"60l"}]},{"grupo":"Dimensões","itens":[{"label":"Pneus dianteiros","valor":"9.5-24R1"},{"label":"Pneus traseiros","valor":"16.9-28 R1"},{"label":"Raio de giro c/ uso freio","valor":"3800 mm"},{"label":"Raio de giro s/ uso freio","valor":"4200 mm"},{"label":"Contrapesos dianteiros","valor":"8x27 kg"},{"label":"Contrapesos traseiros","valor":"4x40 kg"},{"label":"Comprimento máximo","valor":"3850mm"},{"label":"Distância entre eixos","valor":"2220mm"},{"label":"Altura mínima do solo","valor":"350mm"},{"label":"Altura máxima (até o volante)","valor":"2200mm"},{"label":"Peso em ordem de marcha (embarque)","valor":"2970mm"},{"label":"Peso em ordem de marcha (lastrado)","valor":"3345 kg"}]},{"grupo":"Posto de operação","itens":[{"label":"Tipo","valor":"Plataforma com teto e ROPS ou Cabine com Ar Condicionado"}]},{"grupo":"Itens de série","itens":[{"label":"Retrovisor direito","valor":"X"},{"label":"Painel de instrumentos digitais","valor":"X"},{"label":"Farol de Trabalho Traseiro","valor":"X"}]}]'::jsonb where slug = 'mahindra-6065';

-- 6075 -> mahindra-6075 (8 grupos)
update catalogo_produtos set especificacoes_detalhadas = '[{"grupo":"Motor","itens":[{"label":"Motor","valor":"MAHINDRA MSI 475"},{"label":"Tipo","valor":"Diesel, refrigerado a agua e injecao direta, turbo alimentado"},{"label":"Potencia Maxima","valor":"80 CV @ 2100 RPM*"},{"label":"Torque Máximo","valor":"325 @ 1260 rpm"}]},{"grupo":"Embreagem","itens":[{"label":"Diâmetro do disco (mm)","valor":"304,8"}]},{"grupo":"Tomada de potência (TDP)","itens":[{"label":"Velocidade","valor":"540 @1993 RPM/540E @ 1459 RPM/REVERSÃO"},{"label":"Potencia TDP","valor":"66cv"}]},{"grupo":"Sistema hidráulico","itens":[{"label":"Pressão máxima (kgf/cm²)","valor":"190"},{"label":"Vazão da bomba (L/min)","valor":"58l/min"},{"label":"Capacidade de levante no olhal (kg)","valor":"2600 kg (standard)"}]},{"grupo":"Capacidades","itens":[{"label":"Tanque de combustível","valor":"68l"}]},{"grupo":"Dimensões","itens":[{"label":"Pneus dianteiros","valor":"12.4x24R1"},{"label":"Pneus traseiros","valor":"18.4x30R1"},{"label":"Raio de giro c/ uso freio","valor":"3800 mm"},{"label":"Raio de giro s/ uso freio","valor":"4500 mm"},{"label":"Contrapesos dianteiros","valor":"8x27 kg"},{"label":"Contrapesos traseiros","valor":"4x40 kg"},{"label":"Comprimento máximo","valor":"3850mm"},{"label":"Distância entre eixos","valor":"2220mm"},{"label":"Altura mínima do solo","valor":"390mm"},{"label":"Altura máxima (até o volante)","valor":"2700mm"},{"label":"Peso em ordem de marcha (embarque)","valor":"3170mm"},{"label":"Peso em ordem de marcha (lastrado)","valor":"3545kg"}]},{"grupo":"Posto de operação","itens":[{"label":"Tipo","valor":"Plataforma com teto e ROPS ou Cabine com Ar Condicionado"}]},{"grupo":"Itens de série","itens":[{"label":"Retrovisor direito","valor":"X"},{"label":"Painel de instrumentos digitais","valor":"X"},{"label":"Farol de Trabalho Traseiro","valor":"X"}]}]'::jsonb where slug = 'mahindra-6075';

-- 6075E -> mahindra-6075e (10 grupos)
update catalogo_produtos set especificacoes_detalhadas = '[{"grupo":"Motor","itens":[{"label":"Motor","valor":"Mahindra MSI 475 (MAR-1)"},{"label":"Potencia Maxima","valor":"80 CV @ 2100 RPM*"},{"label":"Torque Máximo","valor":"325 @ 1260 rpm"}]},{"grupo":"Embreagem","itens":[{"label":"Diâmetro do disco (mm)","valor":"304,8"}]},{"grupo":"Tomada de potência (TDP)","itens":[{"label":"Velocidade","valor":"540 @1993 RPM/540E @ 1459 RPM/REVERSÃO"},{"label":"Potencia TDP","valor":"66cv"}]},{"grupo":"Sistema hidráulico","itens":[{"label":"Pressão máxima (kgf/cm²)","valor":"190"},{"label":"Vazão da bomba (L/min)","valor":"58l/min"},{"label":"Capacidade de levante no olhal (kg)","valor":"2600 kg (standard)"}]},{"grupo":"Capacidades","itens":[{"label":"Tanque de combustível","valor":"68 Litros"}]},{"grupo":"Dimensões","itens":[{"label":"Pneus dianteiros","valor":"8.00x18R1"},{"label":"Pneus traseiros","valor":"12.4x28R1"},{"label":"Raio de giro c/ uso freio","valor":"3800 mm"},{"label":"Raio de giro s/ uso freio","valor":"4500 mm"},{"label":"Contrapesos dianteiros","valor":"8x27 kg"},{"label":"Contrapesos traseiros","valor":"4x50 kg"},{"label":"Comprimento máximo","valor":"3850 mm"},{"label":"Distância entre eixos","valor":"2220 mm"},{"label":"Altura mínima do solo","valor":"250 mm"},{"label":"Altura máxima (até o volante)","valor":"1690 mm"},{"label":"Peso em ordem de marcha (embarque)","valor":"3226 kg"},{"label":"Peso em ordem de marcha (lastrado)","valor":"3768 kg"}]},{"grupo":"Bitola","itens":[{"label":"Bitola eixo dianteiro pneu 8.00-R18","valor":"1311 mm"},{"label":"Bitola eixo traseiro pneu 12.4-28R1","valor":"1272 à 1370 mm"},{"label":"Largura Externa Face a Face pneu dianteiro 8.00-R18","valor":"1516 mm"},{"label":"Largura externa face a face pneu traseiro 12.4-28R1","valor":"1580 à 1678 mm"},{"label":"Bitola eixo dianteiro pneu 250/80R18","valor":"1325 mm"},{"label":"Bitola eixo traseiro pneu 14.9-24R1","valor":"1324 mm"},{"label":"Largura Externa Face a Face pneu dianteiro 250/80R18","valor":"1581 mm"},{"label":"Largura externa face a face pneu traseiro 14.9-24R1","valor":"1720 mm"}]},{"grupo":"Posto de operação","itens":[{"label":"Tipo","valor":"Plataforma com teto e ROPS ou Cabine com Ar Condicionado"}]},{"grupo":"Itens de série","itens":[{"label":"Retrovisor direito","valor":"X"},{"label":"Painel de instrumentos digitais","valor":"X"},{"label":"Farol de Trabalho Traseiro","valor":"X"}]},{"grupo":"Equipamentos opcionais","itens":[{"label":"8.00-R18 + 12.4-28R1 (Standard)","valor":"250/80R18 + 12.4-28R1"},{"label":"8.00-R18 + 14.9-24R1","valor":"250/80R18 + 14.9-24R1"}]}]'::jsonb where slug = 'mahindra-6075e';

-- 6675F -> mahindra-6675f (10 grupos)
update catalogo_produtos set especificacoes_detalhadas = '[{"grupo":"Motor","itens":[{"label":"Motor","valor":"Perkins 1104D-44T"},{"label":"Tipo","valor":"Diesel, refrigerado a água e injeção direta, aspirado"},{"label":"Potencia Maxima","valor":"75,5 CV @ 2200RPM"},{"label":"Torque Máximo","valor":"307 Nm @ 1400 rpm"},{"label":"Cilindros/Cilindradas","valor":"4 / 4400 cm³"}]},{"grupo":"Embreagem","itens":[{"label":"Tipo","valor":"Dupla"},{"label":"Diâmetro do disco (mm)","valor":"280"}]},{"grupo":"Tomada de potência (TDP)","itens":[{"label":"Velocidade","valor":"540 @ 2089 RPM / 540E @ 1500 RPM"},{"label":"Potencia TDP","valor":"67cv"}]},{"grupo":"Transmissão","itens":[{"label":"Tipo","valor":"Mecanica sincronizada"},{"label":"Marchas","valor":"16F + 8R"},{"label":"Tração dianteira","valor":"Eletro Hidraulico, acionamento por botao"}]},{"grupo":"Sistema hidráulico","itens":[{"label":"Pressão máxima (kgf/cm²)","valor":"180"},{"label":"Vazão da bomba (L/min)","valor":"48,5L/min"},{"label":"Capacidade de levante no olhal (kg)","valor":"2800 kg"},{"label":"Válvulas de controle remoto","valor":"2"}]},{"grupo":"Direção","itens":[{"label":"Bomba direção","valor":"Engrenagens"}]},{"grupo":"Capacidades","itens":[{"label":"Tanque de combustível","valor":"70L"},{"label":"Lubrificação","valor":"N.D"},{"label":"Motor de partida","valor":"12 V/2 kW"},{"label":"Bateria","valor":"12 V/80 Ah"}]},{"grupo":"Dimensões","itens":[{"label":"Pneus dianteiros","valor":"280/70 R20 R1"},{"label":"Pneus traseiros","valor":"380/70 R28 R1"},{"label":"Contrapesos dianteiros","valor":"8 x 30 Kg"},{"label":"Contrapesos traseiros","valor":"4x40 kg"},{"label":"Comprimento máximo","valor":"4020 mm"},{"label":"Distância entre eixos","valor":"2130 mm"},{"label":"Altura mínima do solo","valor":"260 mm"},{"label":"Altura máxima (até o volante)","valor":"N.D"},{"label":"Peso em ordem de marcha (embarque)","valor":"2750kg"},{"label":"Peso em ordem de marcha (lastrado)","valor":"3110kg"}]},{"grupo":"Posto de operação","itens":[{"label":"Tipo","valor":"Cabine"}]},{"grupo":"Itens de série","itens":[{"label":"Retrovisor direito","valor":"Retrovisor direito e esquerdo"},{"label":"Painel de instrumentos digitais","valor":"Painel de instrumentos digitais"},{"label":"Farol de Trabalho Traseiro","valor":"X"}]}]'::jsonb where slug = 'mahindra-6675f';

-- (8000S e 9500S removidos: modelos descontinuados, não existem mais no catálogo.)

-- 7095 -> mahindra-7095 (7 grupos)
update catalogo_produtos set especificacoes_detalhadas = '[{"grupo":"Motor","itens":[{"label":"Potencia Maxima","valor":"95@2300RPM"}]},{"grupo":"Tomada de potência (TDP)","itens":[{"label":"Velocidade","valor":"540 @ 1993/      540E@1469"},{"label":"Acoplamento","valor":"Mecanico manual"},{"label":"Potencia TDP","valor":"83cv"}]},{"grupo":"Transmissão","itens":[{"label":"Marchas","valor":"15F+15R"},{"label":"Reversor","valor":"Mecânico sincronizado"}]},{"grupo":"Sistema hidráulico","itens":[{"label":"Capacidade de levante no olhal (kg)","valor":"5730 kg"}]},{"grupo":"Freios","itens":[{"label":"Acionamento","valor":"Mecanico"}]},{"grupo":"Capacidades","itens":[{"label":"Tanque de combustível","valor":"90L"},{"label":"Alternador","valor":"12 V/140 Ah"},{"label":"Bateria","valor":"12V/130Ah"}]},{"grupo":"Dimensões","itens":[{"label":"Comprimento máximo","valor":"4241"}]}]'::jsonb where slug = 'mahindra-7095';

-- 86-110P -> mahindra-8110 (10 grupos)
update catalogo_produtos set especificacoes_detalhadas = '[{"grupo":"Motor","itens":[{"label":"Motor","valor":"Perkins/1104-44TA + T3059"},{"label":"Potencia Maxima","valor":"110CV @ 2200RPM"},{"label":"Torque Máximo","valor":"416 @1400RPM"},{"label":"Cilindros/Cilindradas","valor":"4 / 4400cm³"}]},{"grupo":"Embreagem","itens":[{"label":"Tipo","valor":"Hidraulica por pedal"},{"label":"Diâmetro do disco (mm)","valor":"310"},{"label":"Acionamento","valor":"hidráulico por pedal"}]},{"grupo":"Tomada de potência (TDP)","itens":[{"label":"Velocidade","valor":"430 - 540 - 750 (540E) - 1000 (750E)"},{"label":"Acoplamento","valor":"Eletrohidraulico"},{"label":"Potencia TDP","valor":"94cv"}]},{"grupo":"Transmissão","itens":[{"label":"Tipo","valor":"Mecanica sincronizada com reversor"},{"label":"Marchas","valor":"16F +16R (4 velocidades sincronizadas + 1 powershift com.2 grupos H-L + Posicao campo/transporte)"},{"label":"Reversor","valor":"Mecânico sincronizado"},{"label":"Tração dianteira","valor":"Eletro Hidraulico, acionamento por botao"},{"label":"Bloqueio do diferencial","valor":"Eletro Hidraulico, acionamento por botao"}]},{"grupo":"Sistema hidráulico","itens":[{"label":"Tipo","valor":"Gerenciamento eletronico, com controle de posicao, velocidade, profundidade e sensibilidade"},{"label":"Pressão máxima (kgf/cm²)","valor":"190"},{"label":"Vazão da bomba (L/min)","valor":"60l/min"},{"label":"Capacidade de levante no olhal (kg)","valor":"5000kg(Standard)"}]},{"grupo":"Freios","itens":[{"label":"Acionamento","valor":"Hidraulico"}]},{"grupo":"Direção","itens":[{"label":"Bomba direção","valor":"Engrenagens, vazão de 33 litros/minuto"}]},{"grupo":"Capacidades","itens":[{"label":"Tanque de combustível","valor":"110L"},{"label":"Lubrificação","valor":"por bomba independente, com vazao de 36L/min"},{"label":"Alternador","valor":"12 V/120 Ah"},{"label":"Motor de partida","valor":"12 V/3.2kW"},{"label":"Bateria","valor":"12 V/115 Ah"}]},{"grupo":"Dimensões","itens":[{"label":"Pneus dianteiros","valor":"360/70 R28"},{"label":"Pneus traseiros","valor":"480/70 R34"},{"label":"Raio de giro c/ uso freio","valor":"ND"},{"label":"Raio de giro s/ uso freio","valor":"ND"},{"label":"Contrapesos dianteiros","valor":"10 x 30 kg (Longitudinais) + 3 x 50 kg (Em cada roda)"},{"label":"Contrapesos traseiros","valor":"1 x 50 kg (Em cada roda)"},{"label":"Comprimento máximo","valor":"2405"},{"label":"Distância entre eixos","valor":"2405"},{"label":"Altura mínima do solo","valor":"2820"},{"label":"Altura máxima (até o volante)","valor":"415-520mm"},{"label":"Peso em ordem de marcha (embarque)","valor":"4150kg (cabine) 3950 (plataforma)"},{"label":"Peso em ordem de marcha (lastrado)","valor":"4850 (cabine) 4650 (plataforma)"}]},{"grupo":"Posto de operação","itens":[{"label":"Tipo","valor":"Plataforma com teto e ROPS ou Cabine com Ar Condicionado"}]}]'::jsonb where slug = 'mahindra-8110';

-- PASSO 3: conferência.
select slug, jsonb_array_length(especificacoes_detalhadas) as grupos
from catalogo_produtos where slug ilike 'mahindra-%'
and jsonb_array_length(especificacoes_detalhadas) > 0 order by slug;