-- supabase-catalogo-aplicacao.sql
-- Mapa AUTOMÁTICO: produtos.familia_nome (Omie, sujo) -> categoria de aplicação curada.
-- Padrão igual ao de marca: regra por palavra-chave (automático) + override manual + fallback.
-- Idempotente. Não cria FK rígida com o Omie; resolve por texto.

-- =====================================================================
-- 1. TAXONOMIA CANÔNICA DE APLICAÇÃO  (Portas A do showroom)
-- =====================================================================
create table if not exists catalogo_categorias (
  id     text primary key,                 -- slug estável, ex. 'preparo_solo'
  nome   text not null,                     -- rótulo exibido
  ordem  int  not null default 100,         -- ordenação no showroom/menu
  icone  text,                              -- nome do ícone no front
  ativo  boolean not null default true
);

insert into catalogo_categorias (id, nome, ordem, icone) values
  ('tratores',               'Tratores Mahindra',          10, 'tractor'),
  ('preparo_solo',           'Preparo de solo',            20, 'plow'),
  ('plantio_semeadura',      'Plantio e semeadura',        30, 'seedling'),
  ('adubacao_distribuicao',  'Adubação e distribuição',    40, 'spreader'),
  ('pulverizacao',           'Pulverização e proteção',    50, 'spray'),
  ('forragem_pecuaria',      'Forragem e pecuária',        60, 'cow'),
  ('colheita',               'Colheita',                   70, 'harvest'),
  ('transporte_movimentacao','Transporte e movimentação',  80, 'trailer'),
  ('diversos',               'Diversos',                   90, 'box'),
  ('a_classificar',          'A classificar',             999, 'question')
on conflict (id) do nothing;

-- =====================================================================
-- 2. REGRAS AUTOMÁTICAS  (o "automático" — ILIKE por prioridade)
--    prioridade menor = avaliada antes. Mais específico vem primeiro.
-- =====================================================================
create table if not exists catalogo_familia_regra (
  id          bigint generated by default as identity primary key,
  prioridade  int  not null default 100,
  padrao      text not null,                -- ILIKE, ex. '%PULVERIZ%'
  categoria_id text not null references catalogo_categorias(id),
  observacao  text
);

-- Limpa só as regras-semente desta versão antes de re-semear (mantém override intacto)
delete from catalogo_familia_regra where observacao = 'seed_v1';

insert into catalogo_familia_regra (prioridade, padrao, categoria_id, observacao) values
  -- 10: específicas que poderiam colidir com regras genéricas
  (10, '%ENXADA ROTATIVA%', 'preparo_solo',           'seed_v1'),
  -- 20: famílias inequívocas
  (20, '%PLANTADEIR%',      'plantio_semeadura',      'seed_v1'),
  (20, '%SEMEAD%',          'plantio_semeadura',      'seed_v1'),
  (20, '%SULCAD%',          'plantio_semeadura',      'seed_v1'),
  (20, '%PULVERIZ%',        'pulverizacao',           'seed_v1'),
  (20, '%ATOMIZAD%',        'pulverizacao',           'seed_v1'),
  (20, '%POLVILHAD%',       'pulverizacao',           'seed_v1'),
  (20, '%ENSILAD%',         'forragem_pecuaria',      'seed_v1'),
  (20, '%FORRAG%',          'forragem_pecuaria',      'seed_v1'),
  (20, '%ROÇAD%',           'forragem_pecuaria',      'seed_v1'),
  (20, '%ROCAD%',           'forragem_pecuaria',      'seed_v1'),
  (20, '%ENFARD%',          'forragem_pecuaria',      'seed_v1'),
  (20, '%SEGADEIR%',        'forragem_pecuaria',      'seed_v1'),
  (20, '%FENO%',            'forragem_pecuaria',      'seed_v1'),
  (20, '%PICADEIR%',        'forragem_pecuaria',      'seed_v1'),
  (20, '%PICADOR%',         'forragem_pecuaria',      'seed_v1'),
  (20, '%DESINTEGR%',       'forragem_pecuaria',      'seed_v1'),
  (20, '%TRITURAD%',        'forragem_pecuaria',      'seed_v1'),
  (20, '%MISTURAD%',        'forragem_pecuaria',      'seed_v1'),
  (20, '%VAGÃO%',           'forragem_pecuaria',      'seed_v1'),
  (20, '%VAGAO%',           'forragem_pecuaria',      'seed_v1'),
  (20, '%COLHED%',          'colheita',               'seed_v1'),
  (20, '%COLHEITAD%',       'colheita',               'seed_v1'),
  (20, '%PLATAFORM%',       'colheita',               'seed_v1'),
  (20, '%CARRETA%',         'transporte_movimentacao','seed_v1'),
  (20, '%REBOQUE%',         'transporte_movimentacao','seed_v1'),
  (20, '%CONCHA%',          'transporte_movimentacao','seed_v1'),
  (20, '%CARREGADEIR%',     'transporte_movimentacao','seed_v1'),
  (20, '%GUINCHO%',         'transporte_movimentacao','seed_v1'),
  (20, '%GRANELEIR%',       'transporte_movimentacao','seed_v1'),
  (20, '%BASCULANT%',       'transporte_movimentacao','seed_v1'),
  (20, '%TANQUE%',          'transporte_movimentacao','seed_v1'),
  -- 30: distribuição/adubação (depois de plantio p/ não roubar plantadeira)
  (30, '%DISTRIBUID%',      'adubacao_distribuicao',  'seed_v1'),
  (30, '%ADUBAD%',          'adubacao_distribuicao',  'seed_v1'),
  (30, '%ESPALHAD%',        'adubacao_distribuicao',  'seed_v1'),
  (30, '%ESPARRAMAD%',      'adubacao_distribuicao',  'seed_v1'),
  (30, '%CALCAR%',          'adubacao_distribuicao',  'seed_v1'),
  -- 40: preparo de solo genérico
  (40, '%GRADE%',           'preparo_solo',           'seed_v1'),
  (40, '%ARAD%',            'preparo_solo',           'seed_v1'),
  (40, '%SUBSOLAD%',        'preparo_solo',           'seed_v1'),
  (40, '%ESCARIFIC%',       'preparo_solo',           'seed_v1'),
  (40, '%NIVELAD%',         'preparo_solo',           'seed_v1'),
  (40, '%PLAINA%',          'preparo_solo',           'seed_v1'),
  (40, '%LÂMINA%',          'preparo_solo',           'seed_v1'),
  (40, '%LAMINA%',          'preparo_solo',           'seed_v1'),
  -- 50: trator (genérico, por último)
  (50, '%TRATOR%',          'tratores',               'seed_v1');

-- =====================================================================
-- 3. OVERRIDE MANUAL  (família exata -> categoria; vence as regras)
--    Use para corrigir os casos que a regra erra ou que caem em a_classificar.
--    Grave a família exatamente como aparece no Omie (a comparação normaliza UPPER+TRIM).
-- =====================================================================
create table if not exists catalogo_familia_categoria (
  familia_nome  text primary key,
  categoria_id  text not null references catalogo_categorias(id),
  confirmado_por text,
  confirmado_em  timestamptz not null default now()
);

-- =====================================================================
-- 4. RESOLVER: override -> regra (por prioridade) -> fallback
-- =====================================================================
create or replace function resolve_categoria_familia(p_familia text)
returns text
language sql
stable
as $$
  with f as (select upper(trim(coalesce(p_familia, ''))) as fam)
  select coalesce(
    -- 1) override manual
    (select o.categoria_id
       from catalogo_familia_categoria o, f
      where upper(trim(o.familia_nome)) = f.fam
      limit 1),
    -- 2) primeira regra que casa, por prioridade
    (select r.categoria_id
       from catalogo_familia_regra r, f
      where f.fam ilike upper(r.padrao)
      order by r.prioridade, r.id
      limit 1),
    -- 3) fallback
    'a_classificar'
  );
$$;

-- =====================================================================
-- 5. AUDITORIA / CALIBRAÇÃO
--    Toda família real do Omie já classificada + nº de SKUs.
--    Rode isto para ver o que caiu em 'a_classificar' e ajustar regra/override.
-- =====================================================================
create or replace view vw_familia_categoria_resolvida as
select
  p.familia_nome,
  resolve_categoria_familia(p.familia_nome) as categoria_id,
  count(*) as qtd_skus
from produtos p
where p.familia_nome is not null
group by 1, 2
order by (resolve_categoria_familia(p.familia_nome) = 'a_classificar') desc,
         qtd_skus desc;

-- =====================================================================
-- 6. APLICAR NA FICHA CURADA
--    Coluna nova + seed automático a partir da 1ª família do filtro.
--    Só preenche onde ainda está nulo (não sobrescreve curadoria manual).
-- =====================================================================
alter table catalogo_produtos
  add column if not exists categoria_aplicacao text references catalogo_categorias(id);

-- ATENÇÃO: assume filtro_supabase jsonb com chave 'familia_nome' = array de texto.
-- Usa o 1º elemento do array (->> 0). Ajuste caso o shape seja diferente.
update catalogo_produtos cp
set categoria_aplicacao = resolve_categoria_familia(cp.filtro_supabase -> 'familia_nome' ->> 0)
where cp.categoria_aplicacao is null
  and cp.filtro_supabase ? 'familia_nome';

-- Conferência rápida da cobertura das fichas:
-- select coalesce(categoria_aplicacao,'(nulo)') cat, count(*)
-- from catalogo_produtos group by 1 order by 2 desc;
